### ISSUE TITLE
Please add documentation on code architecture

### ISSUE THREAD

**Issue by electronut** [NordicSemiconductor/solar_sensor_beacon#3]
This project is a great low power nRF52 beacon example. It's also a nice demonstration on programming the chip to use the radio - without the SDK and the Softdevice. 

Unfortunately it's very hard to comprehend - especially since all the usual Nordic examples use the SDK and the softdevice.

I think it will benefit nRF52 developers if you improve the README by adding an explanation about the code architecture and provide a background.

**Comment by hanselfberg** [comment]
Thank you.

The Solar Powered Sensor Beacon is actually an example application (i.e. not a part of the SDK). However, it comes with documentation similar to the SDK examples.

The intended entry point for the Solar Powered Sensor Beacon is through our info center ([Solar Powered Sensor Beacon documentation](http://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.nrf52%2Fdita%2Fnrf52%2Fapp_example%2Fsolar_beacon%2Fintroduction.html)) where the documentation is. Unfortunately this is not visible when entering GitHub directly. I think this is something we will try to improve.

Please don't hesitate to let us know what additional information you would like to see documented in our info center.

**Comment by electronut** [comment]
Thanks for the clarification.
